# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Entregable3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Entregable3
  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'TTMVC'
end
